// Game Configuration
export const CONFIG = {
    CANVAS_WIDTH: 1200,
    CANVAS_HEIGHT: 800,
    WAVE_DURATION: 60,
    PLAYER_SIZE: 30,
    ENEMY_SIZE: 25,
    BULLET_SIZE: 5,
    BULLET_SPEED: 8,
    PICKUP_SIZE: 15,
    BOSS_WAVE_INTERVAL: 5, // Boss every 5 waves
};

// Character presets
export const CHARACTERS = [
    {
        id: 'balanced',
        name: '⚖️ Balanced Astronaut',
        description: 'Well-rounded stats for any playstyle',
        stats: {
            maxHealth: 100,
            health: 100,
            speed: 3,
            damage: 10,
            fireRate: 30,
            range: 400,
            projectileCount: 1,
            critChance: 0.1,
            critDamage: 1.5,
            armor: 0,
            dodge: 0,
            lifeSteal: 0,
            pickupRange: 50,
        },
        startWeapon: 'basic',
    },
    {
        id: 'tank',
        name: '🛡️ Tank',
        description: 'High health and armor, slow but sturdy',
        stats: {
            maxHealth: 150,
            health: 150,
            speed: 2,
            damage: 8,
            fireRate: 40,
            range: 350,
            projectileCount: 1,
            critChance: 0.05,
            critDamage: 1.3,
            armor: 5,
            dodge: 0,
            lifeSteal: 0,
            pickupRange: 40,
        },
        startWeapon: 'basic',
    },
    {
        id: 'speedster',
        name: '⚡ Speedster',
        description: 'Fast movement and high fire rate',
        stats: {
            maxHealth: 75,
            health: 75,
            speed: 5,
            damage: 7,
            fireRate: 15,
            range: 400,
            projectileCount: 1,
            critChance: 0.15,
            critDamage: 1.8,
            armor: 0,
            dodge: 0.1,
            lifeSteal: 0,
            pickupRange: 60,
        },
        startWeapon: 'basic',
    },
    {
        id: 'sniper',
        name: '🎯 Sniper',
        description: 'Long range with high critical damage',
        stats: {
            maxHealth: 80,
            health: 80,
            speed: 2.5,
            damage: 20,
            fireRate: 50,
            range: 600,
            projectileCount: 1,
            critChance: 0.3,
            critDamage: 2.5,
            armor: 0,
            dodge: 0,
            lifeSteal: 0,
            pickupRange: 45,
        },
        startWeapon: 'basic',
    },
];
