// Game Configuration
export const CONFIG = {
    CANVAS_WIDTH: 1200,
    CANVAS_HEIGHT: 800,
    WAVE_DURATION: 60,
    PLAYER_SIZE: 30,
    ENEMY_SIZE: 25,
    BULLET_SIZE: 5,
    BULLET_SPEED: 8,
    PICKUP_SIZE: 15,
    BOSS_WAVE_INTERVAL: 5, // Boss every 5 waves
};

// Character presets
export const CHARACTERS = [
    {
        id: 'balanced',
        name: '⚖️ Balanced Astronaut',
        description: 'Well-rounded stats for any playstyle',
        stats: {
            maxHealth: 100,
            health: 100,
            speed: 3,
            damage: 10,
            fireRate: 30,
            range: 400,
            projectileCount: 1,
            critChance: 0.1,
            critDamage: 1.5,
            armor: 0,
            dodge: 0,
            lifeSteal: 0,
            pickupRange: 50,
        },
        startWeapon: 'basic',
    },
    {
        id: 'tank',
        name: '🛡️ Tank',
        description: 'High health and armor, slow but sturdy',
        stats: {
            maxHealth: 150,
            health: 150,
            speed: 2,
            damage: 8,
            fireRate: 40,
            range: 350,
            projectileCount: 1,
            critChance: 0.05,
            critDamage: 1.3,
            armor: 5,
            dodge: 0,
            lifeSteal: 0,
            pickupRange: 40,
        },
        startWeapon: 'basic',
    },
    {
        id: 'speedster',
        name: '⚡ Speedster',
        description: 'Fast movement and high fire rate',
        stats: {
            maxHealth: 75,
            health: 75,
            speed: 5,
            damage: 7,
            fireRate: 15,
            range: 400,
            projectileCount: 1,
            critChance: 0.15,
            critDamage: 1.8,
            armor: 0,
            dodge: 0.1,
            lifeSteal: 0,
            pickupRange: 60,
        },
        startWeapon: 'basic',
    },
    {
        id: 'sniper',
        name: '🎯 Sniper',
        description: 'Long range with high critical damage',
        stats: {
            maxHealth: 80,
            health: 80,
            speed: 2.5,
            damage: 20,
            fireRate: 50,
            range: 600,
            projectileCount: 1,
            critChance: 0.3,
            critDamage: 2.5,
            armor: 0,
            dodge: 0,
            lifeSteal: 0,
            pickupRange: 45,
        },
        startWeapon: 'basic',
    },
    {
        id: 'gunslinger',
        name: '🔫 Gunslinger',
        description: 'Multi-shot specialist with rapid fire',
        stats: {
            maxHealth: 85,
            health: 85,
            speed: 3.5,
            damage: 8,
            fireRate: 20,
            range: 450,
            projectileCount: 3,
            critChance: 0.12,
            critDamage: 1.6,
            armor: 0,
            dodge: 0.05,
            lifeSteal: 0,
            pickupRange: 55,
        },
        startWeapon: 'basic',
    },
    {
        id: 'vampire',
        name: '🧛 Vampire',
        description: 'Drains life from enemies with each hit',
        stats: {
            maxHealth: 90,
            health: 90,
            speed: 2.8,
            damage: 12,
            fireRate: 35,
            range: 380,
            projectileCount: 1,
            critChance: 0.08,
            critDamage: 1.4,
            armor: 2,
            dodge: 0.05,
            lifeSteal: 0.2,
            pickupRange: 50,
        },
        startWeapon: 'basic',
    },
    {
        id: 'berserker',
        name: '⚔️ Berserker',
        description: 'High damage but risky - glass cannon',
        stats: {
            maxHealth: 60,
            health: 60,
            speed: 4,
            damage: 18,
            fireRate: 25,
            range: 350,
            projectileCount: 1,
            critChance: 0.25,
            critDamage: 2.0,
            armor: 0,
            dodge: 0.15,
            lifeSteal: 0,
            pickupRange: 48,
        },
        startWeapon: 'basic',
    },
    {
        id: 'engineer',
        name: '🔧 Engineer',
        description: 'Defensive specialist with armor and range',
        stats: {
            maxHealth: 120,
            health: 120,
            speed: 2.2,
            damage: 9,
            fireRate: 38,
            range: 500,
            projectileCount: 1,
            critChance: 0.05,
            critDamage: 1.4,
            armor: 8,
            dodge: 0,
            lifeSteal: 0,
            pickupRange: 65,
        },
        startWeapon: 'basic',
    },
    {
        id: 'medic',
        name: '💊 Medic',
        description: 'Regenerates health over time',
        stats: {
            maxHealth: 110,
            health: 110,
            speed: 2.5,
            damage: 8,
            fireRate: 35,
            range: 400,
            projectileCount: 1,
            critChance: 0.08,
            critDamage: 1.3,
            armor: 3,
            dodge: 0,
            lifeSteal: 0.15,
            pickupRange: 60,
            healthRegen: 0.5,
        },
        startWeapon: 'basic',
    },
    {
        id: 'assassin',
        name: '🗡️ Assassin',
        description: 'High dodge and critical backstab damage',
        stats: {
            maxHealth: 70,
            health: 70,
            speed: 4.5,
            damage: 15,
            fireRate: 28,
            range: 380,
            projectileCount: 1,
            critChance: 0.35,
            critDamage: 3.0,
            armor: 0,
            dodge: 0.25,
            lifeSteal: 0,
            pickupRange: 55,
        },
        startWeapon: 'basic',
    },
    {
        id: 'summoner',
        name: '🔮 Summoner',
        description: 'Spawns helper drones to fight alongside',
        stats: {
            maxHealth: 95,
            health: 95,
            speed: 2.6,
            damage: 6,
            fireRate: 45,
            range: 450,
            projectileCount: 1,
            critChance: 0.1,
            critDamage: 1.5,
            armor: 2,
            dodge: 0.05,
            lifeSteal: 0,
            pickupRange: 70,
            maxDrones: 3,
        },
        startWeapon: 'basic',
    },
    {
        id: 'juggernaut',
        name: '💪 Juggernaut',
        description: 'Extreme tank with knockback immunity',
        stats: {
            maxHealth: 200,
            health: 200,
            speed: 1.5,
            damage: 12,
            fireRate: 50,
            range: 320,
            projectileCount: 1,
            critChance: 0.03,
            critDamage: 1.3,
            armor: 12,
            dodge: 0,
            lifeSteal: 0.1,
            pickupRange: 45,
            knockbackImmune: true,
        },
        startWeapon: 'basic',
    },
];
